general_settings:
  master_key: os.environ/DEFAULT_LITELLM_MASTER_KEY
  database_url: os.environ/DEFAULT_LITELLM_DATABASE_URL
  enable_metrics: true

mcp_servers:
  phoenix:
    url: os.environ/DEFAULT_LITELLM_MCP_PHOENIX_URL
    transport: "http"
    auth_type: "bearer_token"
    auth_value: os.environ/DEFAULT_LITELLM_MCP_PHOENIX_AUTH_VALUE

model_list:
  - model_name: os.environ/DEFAULT_LITELLM_MODEL_NAME
    litellm_params:
      model: os.environ/DEFAULT_LITELLM_MODEL
      api_base: os.environ/DEFAULT_LITELLM_MODEL_API_BASE
      api_key: os.environ/DEFAULT_LITELLM_MODEL_API_KEY
      drop_params: true

  - model_name: kokoro
    litellm_params:
      model: openai/kokoro
      api_base: http://kokoro-api:8000/v1
      api_key: none
    model_info:
      mode: audio
