litellm_settings:
  num_retries: 3
  request_timeout: 300
  drop_params: true
  turn_off_message_logging: true
  json_logs: false

general_settings:
  master_key: os.environ/DEFAULT_LITELLM_MASTER_KEY
  database_url: os.environ/DEFAULT_LITELLM_DATABASE_URL
  enable_metrics: true
  store_model_in_db: true
  default_max_tokens: 262144
  always_include_stream_usage: true
  pass_through_endpoints:
    - path: "/v1/classifier"
      target: "http://classifier:8000"
      include_subpath: true
      methods: ["GET", "POST", "DELETE"]
      forward_headers: true

mcp_servers:
  kokoro_tts:
    url: http://kokoro-api:8000/mcp
    transport: "http"

  phoenix:
    url: os.environ/DEFAULT_LITELLM_MCP_PHOENIX_URL
    transport: "http"
    auth_type: "bearer_token"
    auth_value: os.environ/DEFAULT_LITELLM_MCP_PHOENIX_AUTH_VALUE

model_list:
  - model_name: os.environ/DEFAULT_LITELLM_MODEL_NAME
    litellm_params:
      model: os.environ/DEFAULT_LITELLM_MODEL
      api_base: os.environ/DEFAULT_LITELLM_MODEL_API_BASE
      api_key: os.environ/DEFAULT_LITELLM_MODEL_API_KEY
      max_tokens: 262144

  - model_name: kokoro
    litellm_params:
      model: openai/kokoro
      api_base: http://kokoro-api:8000/v1
      api_key: none
    model_info:
      mode: audio

  - model_name: qwen3.6
    litellm_params:
      model: openai/qwen3.6
      api_base: http://vllm-qwen:8000/v1
      api_key: none
      max_tokens: 32768

  - model_name: qwen2.5-vl
    litellm_params:
      model: openai/Qwen/Qwen2.5-VL-7B-Instruct
      api_base: http://vllm-qwen-vl:8000/v1
      api_key: none
      max_tokens: 8192
    model_info:
      mode: image